datadog:
  image: "datadog/docker-dd-agent"
  privileged: true
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/proc/mounts:/host/proc/mounts:ro"
    - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
  environment:
    - "API_KEY={your_api_key_here}"
    - "HOSTNAME={your_hostname_here}"
